---
title: "Progetto"
subtitle: "cas415"
author: "anna.savino@cogne.com"
version: 1.0 
date: "`r Sys.Date()`"
output:
  rmdformats::readthedown:
    css: ./custom.css
    df_print: paged
    gallery: no
    highlight: default
    html_document: null
    lightbox: yes
    number_sections: yes
    self_contained: yes
    thumbnails: no
editor_options:
  chunk_output_type: console
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE,
                      error = FALSE,
                      fig.height = 7,
                      fig.width = 10,
                      collapse = TRUE,
                      cols.print=20)
rm(list = ls(all.names = TRUE))

require(ggplot2)
require(dplyr)
```

```{r esempio}
data <- mtcars %>% select(disp,mpg)
pl <- ggplot(data) + 
  geom_point(aes(disp,mpg))
print (pl)
```

# Introduzione

Il nostro è il gruppo più **bello** 

+ Chiave: codice_cliente
+ Righe: belli e *ganzi*
