---
title: "Data Discovery "
subtitle: "cas415"
author: "pbrunier@cogne.com"
version: 1.0 
date: "`r Sys.Date()`"
output:
  rmdformats::readthedown:
    css: ./custom.css
    df_print: paged
    gallery: no
    highlight: default
    html_document: null
    lightbox: yes
    number_sections: yes
    self_contained: yes
    thumbnails: no
editor_options:
  chunk_output_type: console
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warning = FALSE,
                      message = FALSE,
                      error = FALSE,
                      fig.height = 7,
                      fig.width = 10,
                      collapse = TRUE,
                      cols.print=20)
rm(list = ls(all.names = TRUE))

require(dplyr)
require(kableExtra)
require(readr)
require(ggplot2)
source('~/dev/cas415/R/function.R')
```

leggiamo i dati 

```{r zerty}
carmet415M3 <- read_rds('/data/cas415/carmet415M3.rds')
                       
```

# analisi variabili risposta

analisi Rm_mean

```{r analisi rm}
pl <- ggplot(carmet415M3)+
  geom_line(aes(index,Rm_mean))+
  geom_point(aes(index,Rm_mean, color=Rm_test1))+
  geom_smooth(aes(index,Rm_mean),method = 'loess', se=FALSE, col='red')+
  geom_line(aes(index, Rm_center))+
  geom_step(aes(index, Rm_usl),color='gray',alpha=.5)+
  geom_step(aes(index, Rm_lsl),color='gray',alpha=.5)

  print(pl)
                       
```

! analisi Rp02_std

```{r analisi rp02}
# pl <- ggplot(carmet415M3)+
#   geom_line(aes(index,Rp02_mean))+
#   geom_smooth(aes(index,Rp02_mean),method = 'loess', se=FALSE, col='red')
#   print(pl)
                       
```

